name: Build
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Initialize environment
        uses: ./.github/actions/init

      - name: Create environment file
        run: |
          echo "CF_TURNSTILE_SECRET_KEY=${{ vars.CF_TURNSTILE_SECRET_KEY }}" >> .dev.vars
          echo "EMAIL_RECIPIENT=${{ vars.EMAIL_RECIPIENT }}" >> .dev.vars
          echo "EMAIL_SENDER=${{ vars.EMAIL_SENDER }}" >> .dev.vars
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .dev.vars

      - name: Build project
        run: npm run build

      - name: Run checks
        run: npm run check
