name: Build Check
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CF_TURNSTILE_SECRET_KEY: ${{ vars.CF_TURNSTILE_SECRET_KEY }}
      CF_TURNSTILE_SITEKEY: ${{ vars.CF_TURNSTILE_SITEKEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Initialize environment
        uses: ./.github/actions/init

      - name: Run build
        run: npm run build
